# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kl.dk.fhir.ffbreporting
canonical: http://fhir.kl.dk/ffbreporting
name: KLFFBReporting
title: "Implementation Guide for FFB reporting (FFB uddatasæt)"
description: Danish municipalities implementation guide for FFB reporting. A standard for reporting social information from citizen journals to a gateway. The aim is to use the data in population based studies and management information systems.
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: release # ci-build # release
status: active # draft # active
publisher:
  name: KL
  url: http://www.kl.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"

dependencies:
  hl7.fhir.dk.core: 1.1.0
  kl.dk.fhir.core: 1.2.0
  kl.dk.fhir.term: 1.0.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  Example: example.html
  Downloads: downloads.html